import type { ReportColumn, ReportDefinition, ReportType } from "@/types/report";

export const REPORT_DEFINITIONS: Record<ReportType, ReportDefinition> = {
  "stok-saat-ini": {
    type: "stok-saat-ini",
    title: "Laporan Stok Saat Ini",
    description: "Memantau stok aktif, minimum stok, dan status ketersediaan per produk.",
    orientation: "landscape",
    sheetName: "Stok Saat Ini",
    filters: ["product", "category", "location", "stockStatus"],
    allowedRoles: ["admin", "petugas_gudang"],
  },
  "stok-per-lokasi": {
    type: "stok-per-lokasi",
    title: "Laporan Stok Per Lokasi",
    description: "Menampilkan distribusi stok per gudang, rak, dan lokasi penyimpanan.",
    orientation: "landscape",
    sheetName: "Stok Per Lokasi",
    filters: ["product", "category", "location", "stockStatus"],
    allowedRoles: ["admin", "petugas_gudang"],
  },
  "stok-masuk": {
    type: "stok-masuk",
    title: "Laporan Stok Masuk",
    description: "Ringkasan transaksi pembelian dan drop barang yang menambah stok.",
    orientation: "landscape",
    sheetName: "Stok Masuk",
    filters: [
      "startDate",
      "endDate",
      "product",
      "category",
      "location",
      "user",
      "transactionType",
    ],
    allowedRoles: ["admin", "petugas_gudang"],
  },
  "pengambilan-barang": {
    type: "pengambilan-barang",
    title: "Laporan Pengambilan Barang",
    description: "Riwayat barang keluar berdasarkan user, keperluan, dan status transaksi.",
    orientation: "landscape",
    sheetName: "Pengambilan",
    filters: [
      "startDate",
      "endDate",
      "product",
      "location",
      "user",
      "transactionStatus",
    ],
    allowedRoles: ["admin", "petugas_gudang", "user"],
  },
  "mutasi-stok": {
    type: "mutasi-stok",
    title: "Laporan Mutasi Stok",
    description: "Jejak lengkap perubahan qty akibat transaksi, koreksi, dan opname.",
    orientation: "landscape",
    sheetName: "Mutasi Stok",
    filters: ["startDate", "endDate", "product", "location", "user", "transactionType"],
    allowedRoles: ["admin", "petugas_gudang"],
  },
  "stock-opname": {
    type: "stock-opname",
    title: "Laporan Stock Opname",
    description: "Hasil sesi opname per lokasi, produk, dan petugas hitung.",
    orientation: "landscape",
    sheetName: "Opname",
    filters: ["startDate", "endDate", "product", "location", "user", "opnameStatus"],
    allowedRoles: ["admin", "petugas_gudang"],
    requiresSignature: true,
  },
  "selisih-opname": {
    type: "selisih-opname",
    title: "Laporan Selisih Opname",
    description: "Fokus pada item opname yang memiliki selisih nilai maupun qty.",
    orientation: "landscape",
    sheetName: "Selisih Opname",
    filters: ["startDate", "endDate", "product", "location", "opnameStatus"],
    allowedRoles: ["admin", "petugas_gudang"],
    requiresSignature: true,
  },
};

export const REPORT_COLUMNS: Record<ReportType, ReportColumn[]> = {
  "stok-saat-ini": [
    { key: "sku", label: "Kode Produk / SKU" },
    { key: "barcode", label: "Barcode Produk" },
    { key: "productName", label: "Nama Produk" },
    { key: "category", label: "Kategori" },
    { key: "unit", label: "Satuan" },
    { key: "location", label: "Lokasi" },
    { key: "availableStock", label: "Stok Tersedia", align: "right", valueType: "number" },
    { key: "minimumStock", label: "Minimum Stok", align: "right", valueType: "number" },
    { key: "stockStatus", label: "Status Stok", valueType: "status" },
    { key: "printedDate", label: "Tanggal Cetak", valueType: "datetime" },
  ],
  "stok-per-lokasi": [
    { key: "locationCode", label: "Kode Lokasi" },
    { key: "locationName", label: "Nama Lokasi" },
    { key: "locationType", label: "Tipe Lokasi" },
    { key: "sku", label: "SKU Produk" },
    { key: "productName", label: "Nama Produk" },
    { key: "category", label: "Kategori" },
    { key: "unit", label: "Satuan" },
    { key: "availableQty", label: "Qty Tersedia", align: "right", valueType: "number" },
    { key: "locationStatus", label: "Status Lokasi", valueType: "status" },
  ],
  "stok-masuk": [
    { key: "transactionCode", label: "Kode Transaksi" },
    { key: "transactionDate", label: "Tanggal Transaksi", valueType: "date" },
    { key: "incomingType", label: "Tipe Masuk" },
    { key: "sourceName", label: "Supplier / Sumber Drop" },
    { key: "productName", label: "Nama Produk" },
    { key: "destinationLocation", label: "Lokasi Tujuan" },
    { key: "qtyIn", label: "Qty Masuk", align: "right", valueType: "number" },
    { key: "purchasePrice", label: "Harga Beli", align: "right", valueType: "currency" },
    { key: "totalValue", label: "Total Nilai", align: "right", valueType: "currency" },
    { key: "createdBy", label: "Dibuat Oleh" },
    { key: "note", label: "Catatan" },
  ],
  "pengambilan-barang": [
    { key: "transactionCode", label: "Kode Transaksi" },
    { key: "pickupDate", label: "Tanggal Pengambilan", valueType: "date" },
    { key: "requesterName", label: "Nama Pengambil" },
    { key: "sourceLocation", label: "Lokasi Asal" },
    { key: "sku", label: "SKU Produk" },
    { key: "productName", label: "Nama Produk" },
    { key: "qtyOut", label: "Qty Diambil", align: "right", valueType: "number" },
    { key: "unit", label: "Satuan" },
    { key: "purpose", label: "Keperluan" },
    { key: "transactionStatus", label: "Status Transaksi", valueType: "status" },
    { key: "note", label: "Catatan" },
  ],
  "mutasi-stok": [
    { key: "transactionDate", label: "Tanggal", valueType: "date" },
    { key: "productName", label: "Produk" },
    { key: "location", label: "Lokasi" },
    { key: "mutationType", label: "Jenis Mutasi" },
    { key: "mutationSource", label: "Sumber Mutasi" },
    { key: "qtyBefore", label: "Qty Sebelum", align: "right", valueType: "number" },
    { key: "qtyChange", label: "Qty Perubahan", align: "right", valueType: "number" },
    { key: "qtyAfter", label: "Qty Sesudah", align: "right", valueType: "number" },
    { key: "createdBy", label: "Dibuat Oleh" },
    { key: "description", label: "Keterangan" },
  ],
  "stock-opname": [
    { key: "sessionCode", label: "Kode Sesi Opname" },
    { key: "sessionName", label: "Nama Sesi" },
    { key: "location", label: "Lokasi" },
    { key: "startedAt", label: "Tanggal Mulai", valueType: "datetime" },
    { key: "finishedAt", label: "Tanggal Selesai", valueType: "datetime" },
    { key: "sessionStatus", label: "Status Sesi", valueType: "status" },
    { key: "productName", label: "Nama Produk" },
    { key: "systemStock", label: "Stok Sistem", align: "right", valueType: "number" },
    { key: "physicalStock", label: "Stok Fisik", align: "right", valueType: "number" },
    { key: "differenceQty", label: "Selisih", align: "right", valueType: "number" },
    { key: "resultStatus", label: "Status Hasil", valueType: "status" },
    { key: "counterName", label: "Petugas Hitung" },
    { key: "note", label: "Catatan" },
  ],
  "selisih-opname": [
    { key: "sessionCode", label: "Kode Sesi" },
    { key: "location", label: "Lokasi" },
    { key: "productName", label: "Produk" },
    { key: "systemStock", label: "Stok Sistem", align: "right", valueType: "number" },
    { key: "physicalStock", label: "Stok Fisik", align: "right", valueType: "number" },
    { key: "differenceQty", label: "Selisih", align: "right", valueType: "number" },
    {
      key: "estimatedDifferenceValue",
      label: "Nilai Estimasi Selisih",
      align: "right",
      valueType: "currency",
    },
    { key: "differenceStatus", label: "Status Selisih", valueType: "status" },
    { key: "note", label: "Catatan" },
    { key: "approvedBy", label: "Approved By" },
    { key: "approvedAt", label: "Approved At", valueType: "datetime" },
  ],
};

export const REPORT_TYPE_OPTIONS = Object.values(REPORT_DEFINITIONS);
